USE 教務系統 
GO
SET IDENTITY_INSERT 好客戶 ON
GO
INSERT INTO 好客戶 (客戶編號, 身份證字號, 姓名)
VALUES (NEXT VALUE FOR 編號順序, 'A333333333' , '王大安')
GO
SET IDENTITY_INSERT 好客戶 OFF
GO
SET IDENTITY_INSERT 好員工 ON
GO
INSERT INTO 好員工 (員工編號, 姓名)
VALUES (NEXT VALUE FOR 編號順序, '王允傑')
GO
INSERT INTO 好員工 (員工編號, 姓名)
VALUES (NEXT VALUE FOR 編號順序, '陳允傑')
GO
SET IDENTITY_INSERT 好員工 OFF
GO
SELECT * FROM 好客戶
GO
SELECT * FROM 好員工
