--範例程式碼6-17：建立SQL帳號，並賦予最小權限
USE [master]
CREATE LOGIN [op] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [msdb]
CREATE USER [op] FOR LOGIN [op]
ALTER ROLE [SQLAgentUserRole] ADD MEMBER [op]
GO
USE [Northwind]
CREATE USER [op] FOR LOGIN [op]
ALTER ROLE [db_backupoperator] ADD MEMBER [op]
