-- 取得所有資料型別
SELECT * FROM sys.types;
-- SELECT CONVERT(NUMERIC(10,5), 1.123456789) AS num;
-- SELECT CONVERT(DECIMAL(10,4), 1.123456789) AS deci;

-- SELECT CONVERT(INT, 1.579) AS intt;
-- SELECT CONVERT(BIGINT, 1.579) AS bint;

-- SELECT CONVERT(FLOAT(5),1.579) AS flo;
-- SELECT CONVERT(REAL, 1.579) AS re;

-- SELECT CONVERT(MONEY, 1.123456789) AS 錢錢;

-- SELECT CONVERT(datetime, GETDATE()) AS 精準時間日期;
-- SELECT CONVERT(smalldatetime, GETDATE()) AS 時間日期;
-- SELECT CONVERT(date, GETDATE()) AS 日期;
-- SELECT CONVERT(time(1), GETDATE()) AS 時間;
-- SELECT CONVERT(datetime2(1), GETDATE()) AS 日期時間;
-- SELECT CONVERT(datetimeoffset, GETDATE()) AS "UTC 日期時間";